// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appContainer': string;
  'content': string;
  'header': string;
  'navigationBar': string;
  'navigationContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
