// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'applicationsContainer': string;
  'applicationsNavigation': string;
  'itemActions': string;
}
export const cssExports: CssExports;
export default cssExports;
