version: '3.1'
services:
  cratis-kernel:
    image: aksioinsurtech/cratis:5.11.0-development
    volumes:
      - ./storage.json:/app/storage.json:ro
    ports:
      - 27017:27017
      - 8080:80
      - 11111:11111
      - 30000:30000
