version: '3.1'
services:
  cratis-kernel:
    image: aksioinsurtech/cratis:8.5.2-development

    volumes:
      - ./cratis.json:/app/cratis.json:ro
    ports:
      - 27017:27017
      - 8080:80
      - 8081:8081
      - 11111:11111
      - 30000:30000

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
