version: '3.1'
services:
  cratis-kernel:
    image: ghcr.io/aksio-insurtech/cratis:6.12.0
    volumes:
      - ./cratis.json:/app/cratis.json:ro
    ports:
      - 27017:27017
      - 8080:80
      - 11111:11111
      - 30000:30000
