name: .NET Build

on:
  push:
    branches:
      - "main"
    paths:
      - "Source/**"
      - "!Source/Web/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "Source/**"
      - "!Source/Web/**"

jobs:
  dotnet-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.400"

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests for root
        run: dotnet test --no-build --configuration Release
